import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Learning Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <a href="">Home</a>
        <a href="/events">Events</a>
        <a href="/about-us">About Us</a>
      </nav>

      <main className={styles.main}>
        {data.map((event)=>{
          return <a key={event.id} href={`/events/${event.id}`}>
            <Image width={200} height={200} src={event.image} alt={event.title} />
            <h2>{event.title}</h2>
            <p>{event.description}</p>
          </a>
        })}
      </main>

      <footer>© 2023 Sayyad Gul Mohammad</footer>
    </div>
  );
}

export async function getServerSideProps(){
  const { events_categories } = await import('/data/data.json');
  return {
      props:{
        data:events_categories
      }
  }
}
